apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-file
  namespace: elsewedy-app
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "ConnectionString": "Server=10.76.0.3;Database=ecatalogdb;User Id=sqlserver;Password=YourStrong@Passw0rd;TrustServerCertificate=True;",
        "DataProvider": "sqlserver",
        "SQLCommandTimeout": 30
      },
      "AzureBlobConfig": {
        "ConnectionString": "",
        "ContainerName": "",
        "EndPoint": "",
        "AppendContainerName": true,
        "StoreDataProtectionKeys": false,
        "DataProtectionKeysContainerName": "",
        "DataProtectionKeysVaultId": ""
      },
      "CacheConfig": {
        "DefaultCacheTime": 66,
        "ShortTermCacheTime": 0,
        "BundledFilesCacheTime": 120
      },
      "CommonConfig": {
        "DisplayFullErrorStack": false,
        "UserAgentStringsPath": "~/App_Data/browscap.xml",
        "CrawlerOnlyUserAgentStringsPath": "~/App_Data/browscap.crawlersonly.xml",
        "UseSessionStateTempDataProvider": false,
        "MiniProfilerEnabled": false,
        "ScheduleTaskRunTimeout": null,
        "StaticFilesCacheControl": "public,max-age=31536000",
        "PluginStaticFileExtensionsBlacklist": "",
        "ServeUnknownFileTypes": false,
        "UseAutofac": true
      },
      "DistributedCacheConfig": {
        "DistributedCacheType": "redis",
        "Enabled": false,
        "ConnectionString": "127.0.0.1:6379,ssl=False",
        "SchemaName": "dbo",
        "TableName": "DistributedCache"
      },
      "HostingConfig": {
        "UseProxy": false,
        "ForwardedProtoHeaderName": "",
        "ForwardedForHeaderName": "",
        "KnownProxies": ""
      },
      "InstallationConfig": {
        "DisableSampleData": false,
        "DisabledPlugins": "",
        "InstallRegionalResources": true
      },
      "PluginConfig": {
        "UseUnsafeLoadAssembly": true
      },
      "WebOptimizer": {
        "EnableJavaScriptBundling": true,
        "EnableCssBundling": true,
        "JavaScriptBundleSuffix": ".scripts",
        "CssBundleSuffix": ".styles",
        "EnableCaching": null,
        "EnableMemoryCache": true,
        "EnableDiskCache": true,
        "EnableTagHelperBundling": false,
        "CdnUrl": null,
        "CacheDirectory": null,
        "AllowEmptyBundle": null,
        "HttpsCompression": 2
      }
    } 
