apiVersion: v1
kind: Service
metadata:
  name: nopcommerce-service
  namespace: elsewedy-app
spec:
  type: ClusterIP
  selector:
    app: nopcommerce
  ports:
    - name: http
      port: 80
      targetPort: 80
        #    - name: https
        #port: 443
        #targetPort: 443
